Repository AlexandreAllard/TPGIT_G4, pull requests merged in 2023-03, with the labels that each got.

#1 Documentation addition to the project
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .gitignore
  LICENSE
  README.md
Labels: documentation

#4 Homepage button on the navbar
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .gitignore
  LICENSE
  README.md
  src/spotify.html
Labels: enhancement

#5 Navbar position fixed under 768px
  css/style.css
Labels: bug

#9 NodeJS action addition to the project
  .github/workflows/node.js.yml
  app.js
  package-lock.json
  package.json
Labels: documentation, enhancement
